### ISSUE TITLE
SVN Install doesn't work

### ISSUE THREAD

**Issue by lwolfsonkin** [Homebrew/homebrew-cask-fonts#1694]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

On my machine, font installations that involve **SVN checkouts of github repositories** do not work. I tested this across a wide range of fonts (various google fonts, as well as powerline fonts that are also SVN download). Note that all these github-backed SVN (`:svn`) installations involve the addition of `/trunk/` to the github URL (as documented [here](https://help.github.com/articles/support-for-subversion-clients/)), leading to a location that itself does not look like a functioning URL (e.g. `https://github.com/google/fonts/trunk/apache/robotomono`, leading to confused issues such as #1015, which I believe are really an instance of the same problem as this issue). In Homebrew/homebrew-cask#16116 it was proposed to remove this SVN download feature in part because of this opaqueness.

#### Command that failed

```
brew cask install font-roboto-mono
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Checking out https://github.com/google/fonts/trunk/apache/robotomono
==> Executing: ["/usr/bin/svn", "checkout", "--force", "--config-option", "config:miscellany:use-commit-times=yes", "--trust-server-cert", "--non-interactive", "https://github.com/google/fonts/trunk/apache/robotomono", "/Users/Lawrence/Library/Caches/Homebrew/Cask/font-roboto-mono--svn"]
Error: Download failed on Cask 'font-roboto-mono' with message: Command failed to execute!

==> Failed command:
/usr/bin/svn checkout --force --config-option config:miscellany:use-commit-times=yes --trust-server-cert --non-interactive https://github.com/google/fonts/trunk/apache/robotomono /Users/Lawrence/Library/Caches/Homebrew/Cask/font-roboto-mono--svn

==> Standard Output of failed command:


==> Standard Error of failed command:
svn: E175002: Unable to connect to a repository at URL 'https://github.com/google/fonts/trunk/apache/robotomono'
svn: E175002: OPTIONS of 'https://github.com/google/fonts/trunk/apache/robotomono': SSL handshake failed: SSL error: tlsv1 alert protocol version (https://github.com)


==> Exit status of failed command:
#<Process::Status: pid 95114 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:42:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:126:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:51:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:75:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.6-4-ge954bed
Homebrew/homebrew-cask (git revision cd305; last commit 2018-05-28)
==> macOS
10.11.6
==> SIP
Enabled
==> Java
9.0.4, 1.8.0_72, 1.7.0_75
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (47 files, 2.0GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3966 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1162 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"
```

#### Output of `brew tap`

```
brewsci/science
fisherman/tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/command-not-found
homebrew/core
homebrew/livecheck
homebrew/science
thoughtbot/formulae
```

**Comment by lwolfsonkin** [comment]
The actual error that is produced is one that SVN emits. Though, when I use **brewed SVN** instead of the system SVN (`/usr/bin/svn` --> `svn`)

```
svn checkout --force --config-option config:miscellany:use-commit-times=yes --trust-server-cert --non-interactive https://github.com/google/fonts/trunk/apache/robotomono /Users/Lawrence/Library/Caches/Homebrew/Cask/font-roboto-mono--svn
```

then **the checkout completes successfully**

```
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/DESCRIPTION.en_us.html
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/LICENSE.txt
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/METADATA.pb
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-Bold.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-BoldItalic.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-Italic.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-Light.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-LightItalic.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-Medium.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-MediumItalic.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-Regular.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-Thin.ttf
A    ~/Library/Caches/Homebrew/Cask/font-roboto-mono--svn/RobotoMono-ThinItalic.ttf
Checked out revision 1359.
```

I'm not sure as to why the native mac SVN on my machine (apparently version 1.7.22) does not complete the checkout correctly but the brewed SVN (version 1.10.0) does work.

I think that the solution here would be forcing `brew-cask` to use brewed svn instead of system svn.  Is that a possibility? This is a change that would have to happen in the main Homebrew/brew repo.

**Comment by lwolfsonkin** [comment]
hmmm. @vitorgalvao. I understand. Is the "weakening security" part referring specifically to doing something to somehow use less secure SSL or something, or is it also a concern to use brewed svn instead of system svn?

**Comment by vitorgalvao** [comment]
The SSL.

**Comment by lwolfsonkin** [comment]
Is it plausible to allow the SVNDownloader to use brewed SVN instead of system SVN? (I could make the PR). (Maybe there's an example of somewhere in brew-core where an extended feature has a dependency as another keg)

**Comment by commitay** [comment]
> I’m wary of possibly weakening security with a workaround

There isn't a workaround for this that would involve weakening security as GitHub refuses TLS1.

We haven't encountered this yet with casks but it has been an issue with a couple of formulae that interact with GitHub e.g. https://github.com/Homebrew/homebrew-core/pull/26401. The solution is pretty much what is suggested, on older systems use a brewed version of the tool (or dependency) that supports the stronger crypto that GitHub enforces.

If this is to be a wontfix we should probably set `depend_on macos: >= :sierra` on SVN casks.

**Comment by lwolfsonkin** [comment]
Bump @vitorgalvao

**Comment by vitorgalvao** [comment]
I’m not opposed to it, though I’m not convinced it’d be worth it for the small use case. Since I’m neutral, I’ll defer to another maintainer who has a stronger opinion on this.

If you can do the changes **without it requiring a lot of work on your part**, it might be worth submitting a PR to discuss there.

**Comment by commitay** [comment]
> I’m not opposed to it, though I’m not convinced it’d be worth it for the small use case.

Same. This hasn't been working since the end of February and this is the first issue we've had about it.

@reitermarkus Any thoughts on this?

**Comment by reitermarkus** [comment]
@reitermarkus Any thoughts on this?

I will be merging the cask download strategies and formula download strategies, so this *may* be fixed once completed.
