### ISSUE TITLE
Install instructions outdated?

### ISSUE THREAD

**Issue by rjhilgefort** [Homebrew/homebrew-cask-fonts#1812]
I just went through an install and fonts aren't available at their bare-word name. You have to install like this:

```
brew cask install homebrew/cask-fonts/font-firacode-nerd-font
```

Not sure if I just did something wrong or what, but that's how I had to install them.

**Comment by reitermarkus** [comment]
You need to run `brew tap homebrew/cask-fonts` first, which has already happened now that you ran it with the fully qualified name.

**Comment by rjhilgefort** [comment]
I ran `brew tap homebrew/cask-fonts` before that the bare word install. Just thought I'd try to mention, suppose we'll see if anyone else has the same issue.

**Comment by reitermarkus** [comment]
`brew cask install font-firacode-nerd-font` should definitely work.
