### ISSUE TITLE
Sudo font installation may report duplicate fonts

### ISSUE THREAD

**Issue by jenskutilek** [Homebrew/homebrew-cask-fonts#1875]
https://github.com/Homebrew/homebrew-cask-fonts/blob/04e4cfd89700bd65637bf4d36e55f0bcc2195770/Casks/font-sudo.rb#L20-L23

Variable font versions of Sudo are installed along the static font versions. This may confuse macOS, as to the system it looks like duplicate fonts are installed.

I suggest installing only static fonts, by removing the highlighted lines.

**Comment by vitorgalvao** [comment]
You’re the author, great!

> This may confuse macOS

May you please expand on that? I’m yet to install variable fonts so I’m unsure of what confusion you refer to.

> I suggest installing only static fonts

Why not install only the variable fonts?

> by removing the highlighted lines

They’re in the same place hierarchically, which means there’s a someone might try to readd them. If they were in a different location (say `sudo/variable/`) it might make the distinction clearer.

**Comment by jenskutilek** [comment]
The variable font would define the same weights as the separate fonts, thus causing a "duplicate fonts installed" warning in Font Book.

Of course you are right about possible confusion when all fonts are in the same folder. I have just [made a new release](https://github.com/jenskutilek/sudo-font/releases/tag/v0.40) in which the family name of the variable font is changed to "Sudo Variable" so all fonts can be installed and used at the same time.

The files with "GX" in the file name were included in the release archive by mistake and should not be there, they have been removed now.

With this new release, it may is sufficient to install the variable font file and have access to all the instances, provided the user runs a recent macOS version (10.13+).
