### ISSUE TITLE
Powerline Fonts

### ISSUE THREAD

**Issue by pankajpatel** [Homebrew/homebrew-cask-fonts#1913]
Font Source: https://github.com/powerline/fonts

Just adding an issue for tracking the progress or other things.

I might find some time to make a PR for this.

**Comment by rensbaardman** [comment]
Current progress:
- [ ] 3270
- [x] [AnonymousPro](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-anonymice-powerline.rb) (Anonymice)
- [ ] Arimo
- [ ] Cousine
- [ ] D2Coding
- [x] [DejaVuSansMono](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-dejavu-sans-mono-for-powerline.rb)
- [x] [DroidSansMono](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-droid-sans-mono-for-powerline.rb)
- [ ] DroidSansMonoDotted
- [ ] DroidSansMonoSlashed
- [x] [FiraMono](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-fira-mono-for-powerline.rb)
- [ ] GoMono
- [ ] Hack
- [x] [Inconsolata-g](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-inconsolata-g-for-powerline.rb)
- [x] [Inconsolata](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-inconsolata-for-powerline.rb) and [bold](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-inconsolata-for-powerline-bold.rb)
- [x] [InconsolataDz](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-inconsolata-dz-for-powerline.rb)
- [ ] InputMono
- [x] [LiberationMono](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-liberation-mono-for-powerline.rb)
- [ ] Meslo Dotted
- [ ] Meslo Slashed
- [x] [Monofur](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-monofur-for-powerline.rb)
- [x] [NotoMono](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-noto-mono-for-powerline.rb)
- [ ] NovaMono
- [ ] ProFont
- [x] [RobotoMono](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-roboto-mono-for-powerline.rb)
- [x] [SourceCodePro](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-source-code-pro-for-powerline.rb)
- [ ] SpaceMono
- [ ] SymbolNeu
- [ ] Terminus
- [ ] Tinos
- [x] [UbuntuMono](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-ubuntu-mono-derivative-powerline.rb)

For sake of completeness, here are other powerline fonts in Cask Fonts:
- [archive version of Meslo for Powerline](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-meslo-for-powerline.rb) (by powerline)
- [Consolas for Powerline](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-consolas-for-powerline.rb)
- [Powerline symbols](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-powerline-symbols.rb) (by powerline)
- [Menlo for Powerline](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-menlo-for-powerline.rb)

**Comment by vitorgalvao** [comment]
Feel free to continue using this issue to track your progress, but I’m closing since it’s not being tackled by maintainers.
