### ISSUE TITLE
Cascadia Code: new "Mono", "MonoPL" and "PL"

### ISSUE THREAD

**Issue by sal0max** [Homebrew/homebrew-cask-fonts#1915]
Cascadia Code added some new alterations with its [newest release](https://github.com/microsoft/cascadia-code/releases/tag/v1911.21): "Mono", "MonoPL" and "PL".
Should they be added to the normal `font-cascadia.rb`, or should new casks be created for each?

In the macOS Font Book app, they appear as separate fonts:

![cascadia](https://user-images.githubusercontent.com/423373/69477177-58656a00-0de3-11ea-8ea2-15b05a8ae19e.png)

**Comment by vitorgalvao** [comment]
If they are available in the same archive, add them to the same cask.
