### ISSUE TITLE
Error due to missing ricty_diminished-4.1.1.tar.gz

### ISSUE THREAD

**Issue by uryossa** [Homebrew/homebrew-cask-fonts#1926]
Since "http://www.rs.tus.ac.jp/yyusa/ricty_diminished.html" cannot be accessed, an error occurs during brew cask install.

% brew cask install font-ricty-diminished
==> Downloading https://www.rs.tus.ac.jp/yyusa/ricty_diminished/ricty_diminished-4.1.1.tar.gz
#=#=#
curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'font-ricty-diminished' with message: Download failed: https://www.rs.tus.ac.jp/yyusa/ricty_diminished/ricty_diminished-4.1.1.tar.gz

Ricty Diminished has moved to new homepage.

http://www.yusa.lab.uec.ac.jp/~yusa/ricty_diminished.html
http://www.yusa.lab.uec.ac.jp/~yusa/ricty_diminished/ricty_diminished-4.1.1.tar.gz

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/1927/files
