### ISSUE TITLE
Font Awesome 4

### ISSUE THREAD

**Issue by FranklinYu** [Homebrew/homebrew-cask-fonts#1959]
Would Font Awesome 4 be accepted/reviewed if I do PR? Font Awesome 5 is a breaking change. For example, the LaTeX documents compiled with Font Awesome 4 won’t work for Font Awesome 5. See https://tex.stackexchange.com/questions/132888/fontawesome-font-not-found

**Comment by vitorgalvao** [comment]
Despite being somewhat popular, I’d rather not open the can of worms of having versioned casks for fonts—regular software versioned casks are already a pain to maintain.

However, don’t forget you can host your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).
