### ISSUE TITLE
font-eeyek-unicode download location has been moved

### ISSUE THREAD

**Issue by forivall** [Homebrew/homebrew-cask-fonts#1961]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`brew cask install font-eeyek-unicode` results in:
```
==> Downloading http://tabish.freeshell.org/eeyek/eeyek.zip

curl: (7) Failed to connect to tabish.freeshell.org port 80: Connection refused
Error: Download failed on Cask 'font-eeyek-unicode' with message: Download failed: http://tabish.freeshell.org/eeyek/eeyek.zip
```

Looks like it's been moved to http://tabish.freeshell.org/eeyek/eeyek-ofl.zip (see the [download page](http://tabish.freeshell.org/eeyek/download.html)). Discovered via https://github.com/Homebrew/brew/pull/7043 .

As i'm going through and installing _all the fonts_, i've also discovered the following
`brew cask install font-accordance`
```
==> Downloading https://www.accordancefiles1.com/products/Accordance_Font.zip

curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'font-accordance' with message: Download failed: https://www.accordancefiles1.com/products/Accordance_Font.zip
```
Its [download page](https://www.accordancebible.com/Accordance-Font/) results in a 404, so that may be temporary.

`font-asap`
```
==> Downloading https://www.omnibus-type.com/wp-content/uploads/Asap.zip
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'font-asap', skipping verification.
==> Installing Cask font-asap
==> Purging files for version latest of Cask font-asap
Error: It seems the Font source '/usr/local/Caskroom/font-asap/latest/Asap/Asap-SemiBoldItalic.ttf' is not there.
```

`font-grenze`
```
==> Downloading https://www.omnibus-type.com/wp-content/uploads/Grenze.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'font-grenze'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'font-grenze' does not match.
Expected: ce89d7bf4368eed4656dce1299d914831119813b7e52723b9d18667299e069d0
  Actual: feffcc121f641b3592bb7e4e78fc4f057a534e82a25d419b2f2726186b985928
    File: /Users/forivall/Library/Caches/Homebrew/downloads/29dbced20c0a672d1631e12a700d3ad7a1c8a167cd2d39dc4d8f0a62df658014--Grenze.zip
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
```
`font-hermit`
```
==> Downloading https://pcaro.es/d/otf-hermit-1.21.tar.gz

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
Error: Download failed on Cask 'font-hermit' with message: Download failed: https://pcaro.es/d/otf-hermit-1.21.tar.gz
```

`font-symbola`
```
==> Downloading http://users.teilar.gr/~g1951d/Symbola.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'font-symbola' with message: Download failed: http://users.teilar.gr/~g1951d/Symbola.zip
```
#### Command that failed

```
brew cask install eeyek
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

**Comment by vitorgalvao** [comment]
Thank you for the report but all of these have pitiful download stats. Unless you want to update them, we’ll remove them instead. They’re not worth the maintainer time and effort to update.

**Comment by forivall** [comment]
I think asap, grenze, hermit and symbola are worth fixing (hermit looks like an issue that can just wait for upstream to fix the cert issue). But yeah, eeyek and accordance seem like fonts that are mostly for research material.

**Comment by vitorgalvao** [comment]
The point still stands. If you find them worth fixing, please do (we can help with questions), otherwise might as well remove them.

**Comment by forivall** [comment]
Sure, I'll take a look at fixing them myself.

**Comment by vitorgalvao** [comment]
Are you still interested in tackling these? Otherwise I’ll begin removing them soon.

**Comment by forivall** [comment]
I'll try to make time on the weekend. If you don't hear from me by next week, feel free to delete them, and i might figure it out in the future and re-add them.

**Comment by forivall** [comment]
Yeah, i haven't had time. Feel free to delete them.
