### ISSUE TITLE
Font-inter is out of date

### ISSUE THREAD

**Issue by 0rAX0** [Homebrew/homebrew-cask-fonts#1967]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Inter is currently at version 3.12, this repo install 3.11

#### Command that failed

```
none
```

#### Output of command with `--force --verbose --debug`

```
none
```

#### Output of `brew cask doctor`

```
none
```

#### Output of `brew tap`

```
none
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/1968
