### ISSUE TITLE
nerd-font is outdated

### ISSUE THREAD

**Issue by holymonson** [Homebrew/homebrew-cask-fonts#1992]
All `font-*-nerd-font` and `font-*-nerd-font-mono` need updated, and it added some fonts too. see [releases](https://github.com/ryanoasis/nerd-fonts/releases).

It affects so many cases, I prefer not making PR myself. Hope you would handle them, thanks.

**Comment by holymonson** [comment]
BTW, cask `font-mplus-1mn-nerd-mono` should be `font-mplus-1mn-nerd-font-mono`, normalized with others.

**Comment by vitorgalvao** [comment]
> BTW, cask `font-mplus-1mn-nerd-mono` should be `font-mplus-1mn-nerd-font-mono`, normalized with others.

Fixed. Thank you.

> All `font-*-nerd-font` and `font-*-nerd-font-mono` need updated.

Thank you for the heads-up.

> It affects so many cases, I prefer not making PR myself.

After a short initial setup, [it’s literally one command](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) that does everything for you, including submitting the PR. Example: `font-mplus-1mn-nerd-font-mono --cask-version 2.1.0`.

Even if you just do some it already helps.

> and it added some fonts too

We don’t really care. Maintainers don’t add casks themselves unless they want them. We don’t even accept casks requests. If someone wants the new fonts, they’ll need to add them themselves.

>  Hope you would handle them, thanks.

Nope. We’re all volunteers and I already spend way too much of my free time reviewing all submissions. Considering that, it’s not exactly fair to say “I don’t have the time to do it, so I’ll leave it to you”. We’re all working together, maintainers aren’t free labour.

Fonts are low priority and these are popular, so someone is bound to step up to it.
