### ISSUE TITLE
Google Fonts repository has changed/restructured?

### ISSUE THREAD

**Issue by gallagherman** [Homebrew/homebrew-cask-fonts#2000]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Trying to install fonts that source from https://github.com/google/fonts/trunk/ just hang.

https://github.com/google/fonts/trunk is a 404

Looks like Lora (my example Google font) is no longer at https://github.com/google/fonts/trunk/ofl/lora  but now at https://github.com/google/fonts/tree/master/ofl/lora?

#### Command that failed

```
brew cask install font-lora
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
svn info
==> Cloning https://github.com/google/fonts/trunk/ofl/lora
==> Checking out 50
svn checkout https://github.com/google/fonts/trunk/ofl/lora /Users/mpg/Library/Caches/Homebrew/Cask/font-lora--svn --quiet -r 50 --trust-server-cert --non-interactive
```
Then hangs forever.

#### Output of `brew cask doctor`

```
Your system is ready to brew.
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment]
> Looks like Lora (my example Google font) is no longer at https://github.com/google/fonts/trunk/ofl/lora but now at https://github.com/google/fonts/tree/master/ofl/lora?

You’re not supposed to use the link directly, HBC knows what to do with it.

Whatever is causing the hanging, it seems to be on your side (maybe temporary). I’ve just confirmed it works.

**Comment by gallagherman** [comment]
> it seems to be on your side (maybe temporary).

Ok thanks. Still doesn't work for me. Could be a real HBC bug then?

**Comment by vitorgalvao** [comment]
> Could be a real HBC bug then?

For a feature that has been working for years and you’re the only report of it hanging? No, I’d still bet on it being an issue somewhere on your setup.

**Comment by vsivsi** [comment]
n=2

I am seeing this same issue, on a brand new MacOS install:

```sh
% brew cask install font-crimson-text
==> Cloning https://github.com/google/fonts/trunk/ofl/crimsontext
==> Checking out 50
```

Hangs. No network or processor activity. Never completes.

Other fonts install fine:

```sh
% brew cask install font-3270-nerd-font
==> Downloading https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/3270.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/27574418/7d86ff00-452f-11ea-9c44-eb5b089ecb2f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'font-3270-nerd-font'.
==> Installing Cask font-3270-nerd-font
==> Moving Font '3270-Medium Nerd Font Complete.otf' to '/Users/vsi/Library/Fonts/3270-Medium Nerd Font Complete.otf'.
==> Moving Font '3270 Narrow Nerd Font Complete.otf' to '/Users/vsi/Library/Fonts/3270 Narrow Nerd Font Complete.otf'.
==> Moving Font '3270 Semi-Narrow Nerd Font Complete.otf' to '/Users/vsi/Library/Fonts/3270 Semi-Narrow Nerd Font Complete.otf'.
==> Moving Font '3270-Medium Nerd Font Complete Mono.otf' to '/Users/vsi/Library/Fonts/3270-Medium Nerd Font Complete Mono.otf'.
==> Moving Font '3270 Narrow Nerd Font Complete Mono.otf' to '/Users/vsi/Library/Fonts/3270 Narrow Nerd Font Complete Mono.otf'.
==> Moving Font '3270 Semi-Narrow Nerd Font Complete Mono.otf' to '/Users/vsi/Library/Fonts/3270 Semi-Narrow Nerd Font Complete Mono.otf'.
🍺  font-3270-nerd-font was successfully installed!
```

**Comment by vsivsi** [comment]
@vitorgalvao @gallagherman 

The issue appears to be that in the latest versions of XCode, `svn` is deprecated and no longer seems to work correctly. If this is universally true, then all of the svn based cask fonts will no longer install correctly on fresh MacOS Catalina installs (e.g. all new Macs) with Homebrew installed. If that is indeed the cause, then either `svn` should become a dependency of Homebrew itself or of these svn dependent font casks.

See this SO question for background: 
https://stackoverflow.com/questions/60869347/mac-command-line-tools-11-4-no-longer-has-svn

Workaround solution: Manually running `brew install svn` solved the problem for me. 

```
% brew cask install font-crimson-text
==> Cloning https://github.com/google/fonts/trunk/ofl/crimsontext
==> Checking out 50
==> No SHA-256 checksum defined for Cask 'font-crimson-text', skipping verification.
==> Installing Cask font-crimson-text
==> Moving Font 'CrimsonText-Bold.ttf' to '/Users/vsi/Library/Fonts/CrimsonText-Bold.ttf'.
==> Moving Font 'CrimsonText-BoldItalic.ttf' to '/Users/vsi/Library/Fonts/CrimsonText-BoldItalic.ttf'.
==> Moving Font 'CrimsonText-Italic.ttf' to '/Users/vsi/Library/Fonts/CrimsonText-Italic.ttf'.
==> Moving Font 'CrimsonText-Regular.ttf' to '/Users/vsi/Library/Fonts/CrimsonText-Regular.ttf'.
==> Moving Font 'CrimsonText-Semibold.ttf' to '/Users/vsi/Library/Fonts/CrimsonText-Semibold.ttf'.
==> Moving Font 'CrimsonText-SemiboldItalic.ttf' to '/Users/vsi/Library/Fonts/CrimsonText-SemiboldItalic.ttf'.
🍺  font-crimson-text was successfully installed!
```

**Comment by vitorgalvao** [comment]
Thank you for the investigation, @vsivsi. https://github.com/Homebrew/homebrew-cask/issues/80695.

**Comment by fanninpm** [comment]
Roboto has also been relicensed to the OFL and was upgraded with a variable font. This may render the `roboto-condensed` cask obsolete.
