### ISSUE TITLE
brew cask install font-inconsolata fails, loops endlessly

### ISSUE THREAD

**Issue by melchisadeck** [Homebrew/homebrew-cask-fonts#2012]
#### General troubleshooting steps

 [x ] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Hi All,

On my brand new MacBook Pro 16" running MacOS 10.15.4 I install homebrew and issue the font installation setup command:
$ brew tap homebrew/cask-fonts

Followed by the command to install the Inconsolata font:
$ brew cask install font-inconsolata
==> Cloning https://github.com/google/fonts/trunk/ofl/inconsolata 1

And there it stays, looping infinitely.

Looking at the referenced repo shows that, as of 8 days ago, the Inconsolata font lives at:
https://github.com/google/fonts/ofl/inconsolata 1
and not at the path assumed by brew cask install.

So, the question arises, how to get brew cask install to point at the correct directory on GitHub?

Thanks,
Mel

#### Command that failed

```
brew cask install font-inconsolata
```

#### Output of command with `--force --verbose --debug`

```
$ brew cask install font-inconsolata --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
svn info
==> Cloning https://github.com/google/fonts/trunk/ofl/inconsolata
svn checkout https://github.com/google/fonts/trunk/ofl/inconsolata /Users/melbyrne/Library/Caches/Homebrew/Cask/font-inconsolata--svn --quiet --trust-server-cert --non-interactive
``
...and there it spins.

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.2.13
==> macOS
10.15.4
==> SIP
Enabled
==> Java
1.8.0_241
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3526 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (913 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/core
```

**Comment by fanninpm** [comment]
It seems the [cask formula](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-inconsolata.rb) is looking for files that have been [moved to the `static` subdirectory](https://github.com/google/fonts/tree/master/ofl/inconsolata).

**Comment by vitorgalvao** [comment]
> It seems the [cask formula](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-inconsolata.rb) is looking for files that have been [moved to the `static` subdirectory](https://github.com/google/fonts/tree/master/ofl/inconsolata).

It’s not a “cask formula”, it’s just called “cask”.

And the fix is at https://github.com/Homebrew/homebrew-cask/issues/80695.

**Comment by melchisadeck** [comment]
Ok installed svn as follows:
```
$ brew install svn
```
and then issued the following command as before but now with the following result:
```
$ brew cask install font-inconsolata
==> Cloning https://github.com/google/fonts/trunk/ofl/inconsolata
Updating /Users/melbyrne/Library/Caches/Homebrew/Cask/font-inconsolata--svn
==> No SHA-256 checksum defined for Cask 'font-inconsolata', skipping verification.
==> Installing Cask font-inconsolata
==> Purging files for version latest of Cask font-inconsolata
Error: It seems the Font source '/usr/local/Caskroom/font-inconsolata/latest/Inconsolata-Regular.ttf' is not there.``
```
Any help gratefully received.

Thanks,
Mel

**Comment by vitorgalvao** [comment]
> Error: It seems the Font source '/usr/local/Caskroom/font-inconsolata/latest/Inconsolata-Regular.ttf' is not there.``

https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md

**Comment by fanninpm** [comment]
@vitorgalvao #2016
