### ISSUE TITLE
Font won't install properly, hangs on download. 

### ISSUE THREAD

**Issue by SodaGremlin** [Homebrew/homebrew-cask-fonts#2080]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Font wont install because the google repository moved it from `https://github.com/google/fonts/trunk/ofl/inconsolata` to `https://github.com/google/fonts/tree/master/ofl/inconsolata` (trunk -> tree, and added master)

The install just hangs on the output line: `==> Cloning https://github.com/google/fonts/trunk/ofl/inconsolata` 

#### Command that failed

```
brew cask install font-inconsolata
```

#### Output of command with `--force --verbose --debug`

```
==> Cloning https://github.com/google/fonts/trunk/ofl/inconsolata
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.3.0-53-g13caf6e
==> macOS
10.15.4
==> SIP
Enabled
==> Java
1.8.0_241
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3565 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (963 casks)
/usr/local/Homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk (32 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.39.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
 greggharrington@Greggs-MacBook-Pro  ~  brew tap
adoptopenjdk/openjdk
homebrew/cask
homebrew/cask-fonts
homebrew/core
homebrew/services
weaveworks/tap
```

**Comment by godbout** [comment]
same here with `brew cask install font-roboto-mono`.

**Comment by vitorgalvao** [comment]
The larger hanging issue is already being tracked on https://github.com/Homebrew/homebrew-cask/issues/83818.

As for the specific font casks, you’ve described both the problem and the solution, so we’ll need PRs for those. The fonts repo depends on outside contributions more than the others. Most of these get so few downloads, we’d sooner remove them than spend the time fixing them (because it’s not worth it; if no one cares enough to fix them, no sense in having them).

**Comment by godbout** [comment]
thanks. had no idea. first time i use a cask. i created a PR for Roboto Mono. haven't tested though (3.15am here, time to 😴️). if you need me to test or give additional info, i'll do it tomorrow. the previous URL didn't exist though, that one does.

**Comment by godbout** [comment]
@SodaGremlin try installing `svn` through brew. it's been removed from Xcode and hangs up. solved the issue for me.

**Comment by guidezpl** [comment]
Initially thought this was a link issue, but installing svn through brew worked for me. Might be a good idea to add it as a dependency?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/80695
