### ISSUE TITLE
font-liberation-sans: how to update and its misleading name

### ISSUE THREAD

**Issue by muzimuzhi** [Homebrew/homebrew-cask-fonts#2082]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

**How to update**
From https://pagure.io/liberation-fonts/, the upstream of Liberation Font has moved to [github.com/liberationfonts/liberation-fonts](https://github.com/liberationfonts/liberation-fonts) and its latest release is [2.1.0](https://github.com/liberationfonts/liberation-fonts/releases). Since the cask [`font-liberation-sans`](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-liberation-sans.rb) provides 2.00.1, `font-liberation-sans` needs to update.

When preparing an update with `cask-repair`, I find there is a second variable in its url, apart from the version number. How to handle this? Sample urls of recent Liberation releases:
 * 2.1.0: https://github.com/liberationfonts/liberation-fonts/files/4178407/liberation-fonts-ttf-2.1.0.tar.gz, note the `4178407` in url
 * 2.00.5: https://github.com/liberationfonts/liberation-fonts/files/2926169/liberation-fonts-ttf-2.00.5.tar.gz, note the `2926169` in url

**Misleading cask name**
`font-liberation-sans` installs serif, sans, and mono families of Liberation font. But with the "sans" in its cask name, it is misleading that this cask installs Liberation Sans only. How about renaming it to `font-liberation` or `font-liberation-fonts`?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/2084/files

**Comment by muzimuzhi** [comment]
Many thanks. So it is `#{version.after_comma}` and `#{version.before_comma}` (together with `version '<version>,<extra field>'`) that can be used.

**Comment by vitorgalvao** [comment]
[More are available](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md#version-methods).
