### ISSUE TITLE
optionally install Homebrew Fonts systemwide in /Library/Fonts (feature request?)

### ISSUE THREAD

**Issue by rob-miller** [Homebrew/homebrew-cask-fonts#2092]
I apologise now and first if I have failed to search adequately to find resolution for this.

With a new Catalina Mac (and heplful Touch ID), I am implementing a new security model invoking a separate admin user for installing software (similarly a separate banking user for financial work).  

The only issue I have found thus far is installing fonts, as Homebrew puts them into ~/Library/Fonts instead of /Library/Fonts.  The admin user can write to /Library/Fonts directory without sudo, but symlinking [adminuser]/Library/Fonts into /Library/Fonts doesn't work because of access permissions on [adminuser]/Library.  

In order to make fonts accessible to [normal-user], I need to copy from [adminuser]/Library/Fonts into /Library/Fonts/.  This was slow to work out for the initial installation I needed, and will be a pain for upgrades.  It would be nice if there were a Homebrew install option on fonts to put them into /Library/Fonts, so 'brew cask upgrade' would pick it up and do the right thing.

I experimented briefly with copying to another accessible directory and symlinking to /Library/Fonts/local (so we could have /usr/local/fonts or similar).  [normal-user] can see the files through the symlink, but the MacOS FontBook app does not seem to pick them up.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md#options

> `--fontdir=/my/path` changes the path for Fonts. Default is `~/Library/Fonts`.

It’s also on the `man` page.

**Comment by reidpr** [comment]
This is not at all clear. It really deserves a mention on the cask-fonts README.md.

**Comment by vitorgalvao** [comment]
@reidpr Feel free to submit a PR. Place it before “Installation behind a proxy”, use the same wording as in the linked document and link there as well.
