### ISSUE TITLE
Outdated cask: font-dejavu-sans-mono-for-powerline

### ISSUE THREAD

**Issue by LeoPhong** [Homebrew/homebrew-cask-fonts#2100]
I want to install **DejaVu Sans Mono for Powerline**，so I run `brew cask install font-dejavu-sans-mono-for-powerline`, but the font can not be downloaded. It seems like cloning the font is not work. And I found 

> https://github.com/powerline/fonts/trunk/DejaVuSansMono

this page cannot be found.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask-fonts/pull/2109.
