### ISSUE TITLE
Some fonts has been re-added and do loop on installation

### ISSUE THREAD

**Issue by nicolas-brousse** [Homebrew/homebrew-cask-fonts#2114]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I recently noticed that #2098 re-added some fonts like `aleo`.
For `aleo` it was removed with [this commit](https://github.com/Homebrew/homebrew-cask-fonts/commit/19df2c57ac7b76cd2c1696de244b2a7c6912541c#diff-76f9b6a871db7357ae27c21511f6118c) because of too few download. So I backported it in our own Tap.

Since it was re-added, I have been noticed on `brew update` that the cask exists twice, so I removed it from our Tap. But now, when I try to install the font (`brew cask install font-aleo`), the process seems to retry the installation infinitely.

I tried also with `brew cask install font-abeezee`, and I have similar issue.

I noticed that for the other google fonts, you are using git (or direct download), but for these two fonts, it seems you are using svn. Maybe the issue is related.

#### Command that failed

```
brew cask install font-aleo
# And
brew cask install font-abeezee
```

Maybe there is some others.

#### Output of command with `--force --verbose --debug`

```
% brew cask install font-aleo --force --verbose --debug 
Updating Homebrew...
==> Cloning https://github.com/google/fonts/trunk/ofl/aleo
```

After 5 minutes, the output is still the same.  
I opeened htop while processing to check what happen, and it seems brew retry to svn checkout indefinitively.

#### Output of `brew cask doctor`

```
% brew cask doctor
==> Homebrew Version
2.4.0-53-g748af98
==> macOS
10.15.4
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3583 casks)
/usr/local/Homebrew/Library/Taps/puppetlabs/homebrew-puppet (8 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (154 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1508 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
/usr/local/Homebrew/Library/Taps/pantographe/homebrew-pantographe (5 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.40.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
% brew tap
augmentable-dev/tickgit
buildpack/tap
codeclimate/formulae
delatech/delatech
getsentry/tools
heroku/brew
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
jonof/kenutils
minio/stable
neovim/neovim
pantographe/pantographe
puma/puma
puppetlabs/puppet
rogual/neovim-dot-app
thoughtbot/formulae
```

**Comment by nicolas-brousse** [comment]
By curiosity, I tested `font-advent-pro`, a font that as just been updated, not re-added. And I've got similar issue.

Does the `trunk` branch is still the good one to use with svn protocol on GitHub for google fonts repository?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/80695

**Comment by nicolas-brousse** [comment]
Thanks and sorry for the duplicate.
