### ISSUE TITLE
font-open-sans-hebrew deleted

### ISSUE THREAD

**Issue by ezity** [Homebrew/homebrew-cask-fonts#2115]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

font-open-sans-hebrew has been deleted. I am not sure why, as it is still on the google fonts (alpha) website.

**Comment by vitorgalvao** [comment]
It was deleted by https://github.com/Homebrew/homebrew-cask-fonts/pull/2098, but I can indeed still see it on the Google Fonts repo.

Ping @afeld.
