### ISSUE TITLE
font-montserrat cask should not include 'MontserratAlternates' font files

### ISSUE THREAD

**Issue by bradenmitchell** [Homebrew/homebrew-cask-fonts#2189]
Currently, the [cask](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-montserrat.rb) 'font-montserrat' installs both the regular [Montserrat font](https://fonts.google.com/specimen/Montserrat), as well as the [Montserrat Alternates font](https://fonts.google.com/specimen/Montserrat+Alternates?preview.text_type=alphabet&query=montserrat&preview.size=24).

A separate [cask](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-montserrat-alternates.rb) (font-montserrat-alternates) already exists to install the Montserrat Alternates font on its own, however there is no script to install just the regular Montserrat font.

The font-montserrat cask should be limited to the regular Montserrat font only. Perhaps a 'font-montserrat-family' cask could be used to install the 3 different versions of the font instead.

**Comment by vitorgalvao** [comment]
If you want to take care of it, the fix is to remove the monserrat cask and run the [`import_google_fonts` script](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/developer/bin/import_google_fonts) so it’s replaced with the Google Fonts version.
