### ISSUE TITLE
Any reason to keep on subversion?

### ISSUE THREAD

**Issue by gcbw** [Homebrew/homebrew-cask-fonts#2239]
Before i send in PRs, is there any reason to keep most fonts on subversion instead of git directly?

e.g. https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-ubuntu-mono.rb

**Comment by vitorgalvao** [comment]
Subversion allows us to download only what we need. Without it, every time a user wanted a Google Fonts font, they’d have to download the whole repo.

**Comment by gcbw** [comment]
```

$ git clone --depth 1 --no-checkout --filter=blob:none https://github.com/google/fonts
Cloning into 'fonts'...
remote: Enumerating objects: 1367, done.
remote: Counting objects: 100% (1367/1367), done.
remote: Compressing objects: 100% (1338/1338), done.
remote: Total 1367 (delta 0), reused 611 (delta 0), pack-reused 0
Receiving objects: 100% (1367/1367), 332.11 KiB | 1.42 MiB/s, done.

$ cd fonts

$ git checkout master -- ufl/ubuntumono
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 510 bytes | 510.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 1.98 KiB | 1.98 MiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 696 bytes | 696.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 4.27 KiB | 4.27 MiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 3.69 KiB | 3.69 MiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 364 bytes | 364.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 393 bytes | 393.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 164 bytes | 164.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 105.79 KiB | 533.00 KiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 125.07 KiB | 1.20 MiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 112.62 KiB | 1.08 MiB/s, done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 109.83 KiB | 1.12 MiB/s, done.

$ ls ufl/ubuntumono
CONTRIBUTING.txt		LICENCE-FAQ.txt			TRADEMARKS.txt			UbuntuMono-Italic.ttf
COPYRIGHT.txt			LICENCE.txt			UFL.txt				UbuntuMono-Regular.ttf
DESCRIPTION.en_us.html		METADATA.pb			UbuntuMono-Bold.ttf
FONTLOG.txt			README.txt			UbuntuMono-BoldItalic.ttf
```

all in all, `332.11 KiB` of overhead.

**Comment by vitorgalvao** [comment]
> git clone --depth 1 --no-checkout --filter=blob:none https://github.com/google/fonts

Which is not something `url` does, and that would need to be added as a new feature anyway. Would you be interested in building that?

**Comment by gcbw** [comment]
i see. not really that familiar with brew. 

So that would need a new `using` (`using: shallow`?) feature for `cask.url`? i was initially hopping I could get away with a generic `git_opts` or something :roll_eyes: 

Also, i mostly use brews in corporate environment (can't phantom people inflict OSX on themselves otherwise) where bandwidth is close to infinite. so i am wondering if maybe a fork+`sed -i s/using:      :svn,//` and calling it `homebrew-cask-fonts-wasteful` would be a decent compromise... i do like the new feature better though.

**Comment by vitorgalvao** [comment]
> So that would need a new `using` (`using: shallow`?) feature for `cask.url`? i was initially hopping I could get away with a generic `git_opts` or something

@reitermarkus would be able to better provide those details if you’re interested in pursuing the feature.

> where bandwidth is close to infinite

But disk space isn’t, and you’d download the whole Google Fonts repo once for each font. You could delete the cache after each download, but I wonder if GitHub wouldn’t rate limit you after so many GBs downloaded at once.

**Comment by prem-prakash** [comment]
Github URL raw file is constructed like this: https://raw.githubusercontent.com/user/repository/branch/filename

So, for example, to get google montserrat, it would be:
https://raw.githubusercontent.com/google/fonts/master/ofl/montserrat/Montserrat-Bold.ttf

Then we can get rid of svn, which is a clunky dependency to just download a font, almost as much overhead as downloading the full fonts repo.

Does it make sense? Will a PR be welcome to apply this change?

**Comment by vitorgalvao** [comment]
> Github URL raw file is constructed like this: https://raw.githubusercontent.com/user/repository/branch/filename

Yes, we’re aware, but that’s not sufficient. Were it that simple, it would have been done.

> So, for example, to get google montserrat, it would be:
> https://raw.githubusercontent.com/google/fonts/master/ofl/montserrat/Montserrat-Bold.ttf

Except Montserrat consists of multiple files, and that URL is only getting one of them. So that doesn’t work.

> Then we can get rid of svn, which is a clunky dependency to just download a font, almost as much overhead as downloading the full fonts repo.

In my view, that’s a gross exaggeration.

> Does it make sense? Will a PR be welcome to apply this change?

Not until the above issues are resolved.

**Comment by prem-prakash** [comment]
Ok @vitorgalvao, I agree with your points, but...

There is already a python script reading the METADATA.pb protobuf file, and this file contains each one of the file names needed.

So I suppose that it would be simple to modify https://github.com/Homebrew/homebrew-cask-fonts/blob/master/developer/bin/import_google_fonts to write the casks with the filenames.

Does it make sense?

**Comment by vitorgalvao** [comment]
> Does it make sense?

Still no. What exactly are you suggesting? That we have a cask for each font weight? No way we’re going to do that, maintenance of this repo is hard enough and that would be an awful user experience.

Again, this isn’t something simple that can be fixed by changing the casks themselves. The changes need to happen deeper.

**Comment by prem-prakash** [comment]
"The changes need to happen deeper." What do you mean by that?

I think that it seems pretty simple:

`homebrew-cask` can only run one download command per cask, so even if we could provide one url to each font weight it still would not be able to do the job because it would accept only one url.

I understand that with this current `homebrew-cask` limitation it is not possible for this repo to do something better than using svn.

Thanks for your time and effort.

**Comment by vitorgalvao** [comment]
> "The changes need to happen deeper." What do you mean by that?

That the superficial changes you’re suggesting—modifying the cask files—are not enough. Homebrew’s core itself (or GitHub) needs to suffer changes for this to be viable.
