### ISSUE TITLE
Duplicate cask for M+ fonts

### ISSUE THREAD

**Issue by waldyrious** [Homebrew/homebrew-cask-fonts#2246]
It looks like [`font-mplus.rb`](https://github.com/Homebrew/homebrew-cask-fonts/blob/0eae4813a69742effe0febd8d1f405d710609157/Casks/font-mplus.rb) and [`font-rounded-mplus.rb`](https://github.com/Homebrew/homebrew-cask-fonts/blob/0eae4813a69742effe0febd8d1f405d710609157/Casks/font-rounded-mplus.rb) (introduced in #2178) are duplicates of [`font-m-plus.rb`](https://github.com/Homebrew/homebrew-cask-fonts/blob/0eae4813a69742effe0febd8d1f405d710609157/Casks/font-m-plus.rb) and [`font-rounded-m-plus.rb`](https://github.com/Homebrew/homebrew-cask-fonts/blob/0eae4813a69742effe0febd8d1f405d710609157/Casks/font-rounded-m-plus.rb) (introduced in #146 and #262, respectively).

Should the former be deleted?

**Comment by vitorgalvao** [comment]
> Should the former be deleted?

Delete the latter. The former is auto-generated from a script, so it’s more consistent for the future. There may be others that ended up being duplicated like this.

**Comment by waldyrious** [comment]
The manual entry seems to contain a bunch more styles (1c, 1m, 1mn, 1p, 2c, 2m, 2p) than the automatic one (1p only). These [correspond](https://en.wikipedia.org/wiki/M%2B_FONTS#Naming) to fonts with design differences such as proportional vs. monospaced, etc., so in effect the manual cask does provide a wider variety of fonts than the automatic one. Do we still want to delete it regardless?

**Comment by vitorgalvao** [comment]
The automatic entry will always be recreated when the script is run, so deleting that one is pointless.

To put it bluntly, this repo is a huge time and maintenance drain and isn’t worth the effort, so we need to be efficient. If the script can include those extra versions (are they even in the Google Fonts repo?), so much the better, but that’s the one that needs to stay.

**Comment by waldyrious** [comment]
I'm afraid Google Fonts only includes the 1p version (see [here](https://github.com/Homebrew/homebrew-cask-fonts/blob/master@{2020-08-03}/Casks/font-mplus.rb#L6) and [here](https://github.com/google/fonts/tree/master@{2020-08-03}/ofl)).

I'm not sure removing content that isn't otherwise included is a net positive, compared to having a partial duplicate as is currently the case. I'd like to hear the thoughts of @rolandwalker (#146), @emauricio (#1931), @kaorimatz (#433, #551, #915, #1380), and @izumin5210 (#261, #262) and @brian-c (#176), about whether keeping only the 1p variant would be an acceptable outcome. Otherwise we might as well leave things as they are.

On a separate note, maybe @afeld can also comment on what the automated import would do if the cask name already exists (currently they only differ by a hyphen, `font-mplus` vs `font-m-plus`). Would the content be rewritten? Would there be an error? It would be nice if the Google Fonts version were skipped, since it's a subset of the other one.

**Comment by vitorgalvao** [comment]
> Otherwise we might as well leave things as they are.

Definitely not. We do not want duplicates. This repo is a big enough mess as it is. Everything we can automate is a net win. We’ll not do things that increase the burden of managing this repo.

You’re ignoring the obvious solution that fixes everything for everyone, which is to submit the full font to the Google Fonts repo. HBC shouldn’t be used as a workaround for things missing upstream.

**Comment by waldyrious** [comment]
> You’re ignoring the obvious solution that fixes everything for everyone, which is to submit the full font to the Google Fonts repo. HBC shouldn’t be used as a workaround for things missing upstream.

I wasn't aware that they accepted community contributions, actually — I thought the fonts there were all manually added and curated by a team at Google, or something. I'll look into adding the additional fonts to their M+ collection, then. I'll post back when I have news. Thanks for the heads-up! 👍

**Comment by afeld** [comment]
Since [those font folders](https://github.com/google/fonts/tree/45c7d37c7cd992c63037f5d586f580057a959ce4/ofl/mplus1p) don't contain a metadata file, the import script derives the font name based on the filename:

https://github.com/afeld/homebrew-cask-fonts/blob/95389b1c33f696eebbd8f43d20b72ccd65ab7fd7/developer/bin/import_google_fonts#L172-L173

There's no hyphen there, hence no hyphen in the cask. If a cask of the same name already exists and it points somewhere besides Google Fonts, the script will skip it:

https://github.com/afeld/homebrew-cask-fonts/blob/95389b1c33f696eebbd8f43d20b72ccd65ab7fd7/developer/bin/import_google_fonts#L112-L119

Therefore, the simplest solution is to rename the more complete casks to match what's derived from Google: https://github.com/Homebrew/homebrew-cask-fonts/pull/2250 Does that clarify, and sound reasonable?

**Comment by afeld** [comment]
Re: adding other MPlus styles to Google Fonts: https://github.com/google/fonts/issues/62#issuecomment-415574348

**Comment by waldyrious** [comment]
Thanks for the information and for fixing this @afeld! I've offered to help in the issue you linked to; hopefully we may soon revert this cask to the google fonts version :)
