### ISSUE TITLE
duplicate casks for ubuntu font family

### ISSUE THREAD

**Issue by zhangyoufu** [Homebrew/homebrew-cask-fonts#2255]
#### Description of issue

`font-ubuntu` contains `Ubuntu Mono` and `Ubuntu Condensed`. `font-ubuntu-mono` & `font-ubuntu-condensed` are duplicated. (introduced in #2098)

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/2257
