### ISSUE TITLE
Document subversion issues when behind a proxy

### ISSUE THREAD

**Issue by firesock** [Homebrew/homebrew-cask-fonts#2327]
Recently Ubuntu fonts' method of downloading changed in a way that caused it to fail when updating `font-ubuntu 0.83,fad7939b -> latest` from behind a proxy. 

This seems to be caused by https://github.com/Homebrew/homebrew-cask-fonts/pull/2257 and using Google Fonts as the new upstream, which uses SVN to pull the correct parts of the repo - https://github.com/Homebrew/homebrew-cask-fonts/issues/2239

`svn` ignores the standard `HTTP_PROXY` etc. environment variables, which `git` respects, instead relying on it's own configuration: http://subversion.apache.org/faq.html#proxy. That's not ideal for environments with more dynamic proxies that rely on changing the envvars.

If more fonts are going to be using the Google Fonts/SVN repo, it seems worth documenting these quirks and the limited workaround possible?

(Raised without a template because it's not quite a bug issue, and definitely not a new font cask)

**Comment by vitorgalvao** [comment]
You seem to have more familiarity with the issue than us, so if you want documentation on this, it would help if you started y submitting a PR we can work against.

Otherwise, I doubt it will get done. It’s not a common issue, and I doubt it’s one any maintainer is bumping against.

**Comment by vitorgalvao** [comment]
Closing the issue, but you’re still welcome to submit the PR.
