### ISSUE TITLE
GitHub Actions workflow loop on forked repo

### ISSUE THREAD

**Issue by peterlewis** [Homebrew/homebrew-cask-fonts#2498]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ ] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I updated my fork of this repo, yesterday. This morning I woke up to over 50,000 GitHub Actions notifications.

It appears it was attempting to auto-merge, which it was not able to do on my fork and then hit the re-run and so this repeated, again and again.

I just wanted to let you know, in case the cause of the loop can be found to avoid this happening for other users who fork the repo.

**Comment by reitermarkus** [comment]
At max automerge should be triggered 24 times a day with the currently config, not really seeing how this could ever be in the 10s of thousands.

Without any more concrete information there's nothing we can do here really.

**Comment by peterlewis** [comment]
That's understandable. I notice that my fork was forked by @cschleiden-org, which I am assuming is @cschleiden's GitHub organisation. From his bio it appears that he works for Github onn GitHub Actions, so going to 'at' him here, in case he can help shed any light on causes/mitigations.

**Comment by peterlewis** [comment]
Closing issue as have no further concrete information, which you would understandably need in order to progress this any further.
