### ISSUE TITLE
brew has issues unzipping a .zip archive which contains badly encoded files

### ISSUE THREAD

**Issue by tomy0000000** [Homebrew/homebrew-cask-fonts#2566]
I'm not sure if this is the right place for asking help, but please kindly notice me if there's a better place.

I'm trying to add a font cask, which can be downloaded at `https://moji-waku.com/download/makinas4.zip`. There are three files containing in the archive:
- `Makinas-4-Flat.otf`
- `Makinas-4-Square.otf`
- `dlà¾.txt`

The third file is the LICENSE, but encoded in Windows 1252 format. The builtin archive utility can fully uncompressed the archive, but not when using the unzip cli in homebrew. The error log looks like this:
```
==> Downloading https://moji-waku.com/download/makinas4.zip
Already downloaded: /Users/tomy0000000/Library/Caches/Homebrew/downloads/11c6f88776a78025071787832ab5035b7f4043a208d583f68fcf948fa38d847c--makinas4.zip
==> No SHA-256 checksum defined for Cask 'font-makinas', skipping verification.
==> Installing Cask font-makinas
==> Purging files for version latest of Cask font-makinas
Error: Failure while executing; `unzip -qq -o /Users/tomy0000000/Library/Caches/Homebrew/downloads/11c6f88776a78025071787832ab5035b7f4043a208d583f68fcf948fa38d847c--makinas4.zip -d /var/folders/y5/mnvhssxj26zdcmhgmyp90xv40000gn/T/d20201105-4655-1kdiz9s` exited with 50. Here's the output:
error:  cannot create /var/folders/y5/mnvhssxj26zdcmhgmyp90xv40000gn/T/d20201105-4655-1kdiz9s/makinas4/�d�l���.txt
        Illegal byte sequence
```

Is there a way to fix/get around this?

**Comment by vitorgalvao** [comment]
> Is there a way to fix/get around this?

Yes, but it’s hacky. You’d need to use a [`preflight`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md) and unpack it with another utility, such as `ditto`. That’s not something we generally want to do, especially for a font cask (not worth the trouble).

You can ask upstream to change the encoding of that file.
