### ISSUE TITLE
Follow the naming policy of the upstream project

### ISSUE THREAD

**Issue by heavywatal** [Homebrew/homebrew-cask-fonts#3867]
Like it or not, ["Source Sans Pro" has been renamed to "Source Sans 3"](https://github.com/adobe-fonts/source-sans/issues/192). According to this decision, `font-source-sans-pro` should stick to "Source Sans Pro v2.xxx", and a new formula `font-source-sans-3` (or `font-source-sans@3`?) should be added to track "Source Sans 3".  [Source Serif 4](https://github.com/adobe-fonts/source-serif/issues/77) likewise.

**Comment by vitorgalvao** [comment]
Please submit a PR so we can properly discuss it.
