### ISSUE TITLE
Install fonts globally for all system users?

### ISSUE THREAD

**Issue by lougreenwood** [Homebrew/homebrew-cask-fonts#4062]
I recently built a set of scripts which will setup a new Mac to my needs.

I use my Mac with 2 accounts, an admin account which is used infrequently for upgrades etc and also a standard user account, which is my day to day account.

I run my system setup script as the admin user, this installs all of my brew dependencies, including some fonts from this repo.

However, fonts installed using an admin account whilst not using `sudo` will not be globally installed. Instead it seems that each user must then do a `brew install` so that the fonts are installed locally to that account - this usually isn't a problem that surfaces for typical brew casks, since something in `/usr/local/bin` is available to all users. However, this becomes a problem for font installation when a `standard` MacOS user attempts to run `brew reinstall --cask some-font`, since `brew` will complain that the directories are not writable, and `standard` users are not able to `sudo` (and probably changing ownership of the Homebrew dirs is not recommended for the non-admin user anyway).

Has this issue come up before? Is there any solution to it that I might be missing?

**Comment by vitorgalvao** [comment]
From the `man` page:

```
--fontdir
              Target location for Fonts (default: ~/Library/Fonts).
```

**Comment by lougreenwood** [comment]
Thanks @vitorgalvao that's really useful.

As a followup, do you have any suggestion on how to handle that when using `brew bundle`, e.g the font is installed automatically from a `Brewfile` - perhaps there's an env var I can set?
