### ISSUE TITLE
Cascadia Code does not include italics

### ISSUE THREAD

**Issue by Mellbourn** [Homebrew/homebrew-cask-fonts#4065]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

The [Cascadia Code release 2105.24](https://github.com/microsoft/cascadia-code/releases/tag/v2105.24) now includes the Italic version.

`brew install font-cascadia-code` and `brew install font-cascadia-code-pl` do not install the italic versions. Could you please update them to do so?

### Command that failed

brew install font-cascadia-code-pl

### Output of command with `--verbose --debug`

N/A

### Output of `brew doctor --verbose`

N/A

### Output of `brew tap`

N/A

**Comment by vitorgalvao** [comment]
Please try a PR. [Casks are very simple](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-cascadia-code.rb) and unless they have changed the structure, it will be a straightforward change.

**Comment by Rylan12** [comment]
PR is open: #4064

**Comment by vitorgalvao** [comment]
> PR is open: #4064

It bumps the version, but doesn’t add the italics.

**Comment by Rylan12** [comment]
Reopening until the italics have been added to the other `font-cascadia-*` casks, too

**Comment by Rylan12** [comment]
Okay, now all have been updated

**Comment by Mellbourn** [comment]
Are the Italics really registered in the correct way?

The thing is that I can't get Cascadia Code italics to work properly in iTerm2. If I test with `JetBrains Mono`, italics work immediately.

I've noticed that in Font Book Cascadia Code Italics looks like a completely separate font. While for JetBrains Mono, the italics version is registered under the same font name. Isn't that a problem? How is iTerm2 supposed to understand to use a completely separate font for italics?

This is how JetBrains Mono italics are listed, which work
![image](https://user-images.githubusercontent.com/1785727/120812731-8b96c680-c54d-11eb-8a05-5eaeb2937098.png)

This is how Cascadia Code is listed
![image](https://user-images.githubusercontent.com/1785727/120812788-9a7d7900-c54d-11eb-945d-2ce4654948ce.png)

**Comment by Mellbourn** [comment]
This problem seems related to https://github.com/microsoft/cascadia-code/issues/481
It is fixed in https://github.com/microsoft/cascadia-code/pull/482 which has not been released yet.

More important to homebrew: Some italic font files will be removed: https://github.com/microsoft/cascadia-code/pull/482/commits/3f2f269ac665545a0a0a2d95b7da62dbca8871a8
