### ISSUE TITLE
[Font Request] Scientifica, or bitmap fonts

### ISSUE THREAD

**Issue by shaunsingh** [Homebrew/homebrew-cask-fonts#4282]
Hi, I noticed there weren't any good bitmap fonts available. Maybe consider adding [scientifica](https://github.com/NerdyPepper/scientifica)?

**Comment by carlocab** [comment]
Hi there,

At the moment we don’t take cask requests. If you want a cask added, submit a [pull request](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask).

This message should actually be part of our [issue template](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/.github/ISSUE_TEMPLATE/03_cask_request.yml), but it doesn't quite work properly at the moment.

Feel free to ask if you need any help with this.

**Comment by shaunsingh** [comment]
Sorry about the disturbance, thanks!

**Comment by carlocab** [comment]
Sure. Scientifica looks like a nice font. It would be great if you could open a pull request to add it.

This guide may also help: https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md
