### ISSUE TITLE
fontbureau.com is down, font-input download URLs are broken

### ISSUE THREAD

**Issue by aldanor** [Homebrew/homebrew-cask-fonts#4955]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

fontbureau.com has been down for a few days, does anyone know if it's supposed to get back up or is it down for good? Either way, `font-input` URLs are broken.

### Command that failed

brew install --cask font-input

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>
curl: (7) Failed to connect to input.fontbureau.com port 443: Connection refused
Error: Download failed on Cask 'font-input' with message: Download failed: https://input.fontbureau.com/build/?basic=1&fontSelection=whole&a=0&g=0&i=0&l=0&zero=0&asterisk=0&lineHeight=1.2&accept=I+do
</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>
</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>
</code></pre></details>

**Comment by miccal** [comment]
Ping @djrrb.

**Comment by djrrb** [comment]
Thanks for the ping! I moved the site to my domain, so I just added a PR with URL change...I’ll let you close this if you think this resolves the issue. Cheers! :-D
