### ISSUE TITLE
font-fira-code does not install all the fonts.

### ISSUE THREAD

**Issue by mmynsted** [Homebrew/homebrew-cask-fonts#5396]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

[font-fira-code](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-fira-code.rb) does not install all six Fira-code from the zip archive referenced in the ruby code. The version I am am attempting to use references Fira-code version `6.2`. The archive can be obtained from the Fira-code size here: 
[Fira_Code_v6.2.zip](https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip)

The zip archive contains the following `ttf` fonts.

```
FiraCode-Bold.ttf
FiraCode-Light.ttf
FiraCode-Medium.ttf
FiraCode-Regular.ttf
FiraCode-Retina.ttf
FiraCode-SemiBold.ttf
```

The code here:

```ruby
cask "font-fira-code" do
  version "6.2"
  sha256 "0949915ba8eb24d89fd93d10a7ff623f42830d7c5ffc3ecbf960e4ecad3e3e79"

  url "https://github.com/tonsky/FiraCode/releases/download/#{version}/Fira_Code_v#{version}.zip"
  name "Fira Code"
  homepage "https://github.com/tonsky/FiraCode"

  font "variable_ttf/FiraCode-VF.ttf"
end
```

Each time I install, uninstall, etc. the command references the fonts as a single font named `FiraCode-VF.ttf`. That is not a font that I appear to be able to make use of. I do not see a font with that name in the archive.

Example:
```
Moving Font 'FiraCode-VF.ttf'
```

I force removed, cleaned my cache, etc of `font-fira-code` then ran:

```sh
brew tap homebrew/cask-fonts
brew install --cask font-fira-code
```

This did not result in an error. The problem is that performing the install did not install `Fira-code` fonts in a way that I could use them. 

as instructed [here](https://github.com/tonsky/FiraCode/wiki/Installing). 

This failed to install the fonts in a way useful to me. However, by extracting the zip archive and installing manually, I was able to get each font installed. 

### Command that failed

brew install --cask font-fira-code

### Output of command with `--verbose --debug`

```shell
It does not error as it appears the code does not intend to install each of the fonts.
```

### Output of `brew doctor --verbose`

```shell
Not applicable.
```

### Output of `brew tap`

```shell
...
homebrew/cask-fonts
...
```
```

**Comment by bevanjkay** [comment]
@mmynsted Generally we prefer to install the `variable` font version as opposed to the static fonts unless there is specific issue in doing so. The other six fonts should be available as a part of the how the variable font is setup upstream.

**Comment by rexbinary** [comment]
It seems FiraCode-Retina is not installed by brew using this variable font version. All the other fonts are installed.

**Comment by rexbinary** [comment]
https://github.com/tonsky/FiraCode/issues/1318

It seems removing FiraCode-Retina from FiraCode-VF.ttf was by design. If the preference is to install variable fonts only, then FiraCode-Retina will need to be manually installed separately. I suppose FiraCode-Retina could be it's own package if someone cared to maintain it.

**Comment by miccal** [comment]
Is the `FiraCode-Retina.ttf` font the only one missing from `FiraCode-VF.ttf`?

**Comment by rexbinary** [comment]
Yes, that is the only one missing.

**Comment by mmynsted** [comment]
Thank you. :-)
