### ISSUE TITLE
Google Fonts with broken homepages

### ISSUE THREAD

**Issue by rotu** [Homebrew/homebrew-cask-fonts#5817]
All fonts added in #5816 have broken homepage urls:

`brew home font-finlandica font-gentium-plus-book font-kantumruy-pro font-kdam-thmor-pro font-tai-heritage-pro`

e.g.

`brew home font-gentium-plus-book`
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/119948/168493914-03989b6f-267e-4681-b460-ed8d8760db02.png">

_Originally posted by @rotu in https://github.com/Homebrew/homebrew-cask-fonts/issues/5816#issuecomment-1127033890_

**Comment by bevanjkay** [comment]
This seems to be because the fonts have been added to the GitHub repo, however they are not yet available on https://fonts.google.com

**Comment by rotu** [comment]
> This seems to be because the fonts have been added to the GitHub repo, however they are not yet available on https://fonts.google.com

Makes sense. But these fonts *do* have proper homepages as indicated in the METADATA.pb files. e.g.

https://github.com/google/fonts/blob/3be6b49def6a786e17b914834a9134569676cec2/ofl/finlandica/METADATA.pb
https://github.com/google/fonts/blob/9e5c3e4c84ffc42cfd2c5bad83b75fde386a2bbc/ofl/gentiumplusbook/METADATA.pb

I think they should be citing the maintained homepage, not the (nonexistent in these cases, but usually indirect) Google Fonts page.

Other affected fonts seem to include those introduced in #5705

**Comment by bevanjkay** [comment]
@rotu I can't see a homepage listed in those metadata files. There is a repository URL, however they aren't the actual homepages.

**Comment by rotu** [comment]
> There is a repository URL, however they aren't the actual homepages.

You are right, those are the repository URLs, but I'd be perfectly happy for `brew home` to take me there.

Here are the more canonical homepages, respectively:
- http://finlandica.fi/
- https://software.sil.org/gentium/

Certainly the scripts shouldn't be adding a URL to a nonexistent site!

**Comment by bevanjkay** [comment]
@rotu You are welcome to open a PR to suggest the changes.

https://github.com/Homebrew/homebrew-cask-fonts/blob/master/developer/bin/import_google_fonts#L90-L94

Would need to check for `self.source.repository` and if it exists return it as the homepage.
