### ISSUE TITLE
BrewTestBot incorrectly deleted 4 Google Fonts

### ISSUE THREAD

**Issue by rensbaardman** [Homebrew/homebrew-cask-fonts#6964]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

In December, BrewTestBot [deleted the casks for four Google Fonts](https://github.com/Homebrew/homebrew-cask-fonts/commit/5c3c6ba81e2faf5785c43f03050585b689583a5b):
- Casks/font-fraunces.rb
- Casks/font-gulzar.rb
- Casks/font-open-sans-condensed.rb
- Casks/font-recursive.rb

However, only Open Sans Condensed [was removed from the Google Fonts repository](https://github.com/google/fonts/pull/5518), and the other three fonts are still available from Google Fonts. Their casks have not been re-added since.

What might have triggered this deletion was the addition of [`minisite_url` metadata to those fonts](https://github.com/google/fonts/commit/4fd6ab1bdcfc43ade3dbd1c04c9137c35fdcf9a7) a day earlier. (Note that the metadata for Space Grotesk was also updated, but the cask for that font [points directly to the developers repo](https://github.com/Homebrew/homebrew-cask-fonts/blob/39d6989a4a1060cff93920543101ecd426929529/Casks/font-space-grotesk.rb)).

Reviewing the other commits from the [`google-fonts` workflow](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/.github/workflows/google-fonts.yml), I think this is the only faulty one – it must have tripped on that metadata somehow.

### Command that failed

N/A

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor --verbose`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

**Comment by p-linnane** [comment]
CC @reitermarkus

**Comment by reitermarkus** [comment]
@rensbaardman, your suspicion of this being caused seems correct. We skip casks when the `METADATA.pb` file cannot be parsed. When removing the `try` block, it fails with

```
google.protobuf.text_format.ParseError: 18:1 : Message type "google.fonts_public.FamilyProto" has no field named "minisite_url".
```

**Comment by reitermarkus** [comment]
Seems like this field was added to `gftools` here https://github.com/googlefonts/gftools/commit/280d894312238c478534a44695868505d9d6b85d and a new version released yesterday, but `pip` is still installing the previous version as of right now.

**Comment by reitermarkus** [comment]
Seems like their CI failed to release to PyPi: https://github.com/googlefonts/gftools/issues/649

**Comment by rensbaardman** [comment]
The fonts are added again in the [latest BrewTestBot PR](https://github.com/Homebrew/homebrew-cask-fonts/pull/7077), so assuming that PR will be merged, this issue has been resolved.
