### ISSUE TITLE
Hack Nerd Font - now some symbols

### ISSUE THREAD

**Issue by ucomru** [Homebrew/homebrew-cask-fonts#7574]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

1) After updating "font-hack-nerd-font" there are some symbols looks like "?"
"broken" symbols: 
<img width="138" alt="image" src="https://github.com/Homebrew/homebrew-cask-fonts/assets/101626426/725eec6f-2e15-40b9-9242-8d5ac5ad54ad">

2) "font-fira-code" all nerd symbols shows like "?".

===========================================================================

❯ brew info font-hack-nerd-font
==> font-hack-nerd-font: 3.0.0
https://github.com/ryanoasis/nerd-fonts
/opt/homebrew/Caskroom/font-hack-nerd-font/3.0.0 (14 files, 5.0KB)
From: https://github.com/Homebrew/homebrew-cask-fonts/blob/HEAD/Casks/font-hack-nerd-font.rb
==> Name
Hack Nerd Font (Hack)
==> Description
Developer targeted fonts with a high number of glyphs
==> Artifacts
HackNerdFontPropo-Regular.ttf (Font)
HackNerdFont-BoldItalic.ttf (Font)
HackNerdFont-Italic.ttf (Font)
HackNerdFont-Regular.ttf (Font)
HackNerdFontMono-Bold.ttf (Font)
HackNerdFontMono-BoldItalic.ttf (Font)
HackNerdFontMono-Italic.ttf (Font)
HackNerdFontMono-Regular.ttf (Font)
HackNerdFontPropo-Bold.ttf (Font)
HackNerdFontPropo-BoldItalic.ttf (Font)
HackNerdFontPropo-Italic.ttf (Font)
HackNerdFont-Bold.ttf (Font)

===========================================================================

❯ brew info font-fira-code
==> font-fira-code: 6.2
https://github.com/tonsky/FiraCode
/opt/homebrew/Caskroom/font-fira-code/6.2 (22 files, 1.7MB)
From: https://github.com/Homebrew/homebrew-cask-fonts/blob/HEAD/Casks/font-fira-code.rb
==> Name
Fira Code
==> Description
Free monospaced font with programming ligatures
==> Artifacts
ttf/FiraCode-Bold.ttf (Font)
ttf/FiraCode-Light.ttf (Font)
ttf/FiraCode-Medium.ttf (Font)
ttf/FiraCode-Regular.ttf (Font)
ttf/FiraCode-Retina.ttf (Font)
ttf/FiraCode-SemiBold.ttf (Font)

### Command that failed

brew update && brew upgrade

### Output of command with `--verbose --debug`

```shell
I used 
brew remove --force font-hack-nerd-font font-fira-code
& install/
```

### Output of `brew doctor` and `brew config`

```shell
❯ brew doctor
Your system is ready to brew.

❯ brew config
HOMEBREW_VERSION: 4.0.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0f8068573bbf886fdc78d3f9daca54d53e7e49e
Last commit: 6 days ago
Core tap JSON: 13 May 20:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: Dracula
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
❯ brew tap
homebrew/cask-fonts
```

**Comment by Finii** [comment]
You should probably raise the issue at Nerd Fonts ;-)

https://github.com/ryanoasis/nerd-fonts/issues
