### ISSUE TITLE
google-fonts workflow incorrectly removed fonts

### ISSUE THREAD

**Issue by toobuntu** [Homebrew/homebrew-cask-fonts#8087]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

PR #8085 from the [google-fonts](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/.github/workflows/google-fonts.yml) workflow incorrectly removed fonts still present on Google Fonts. I didn't check all of them, but the two that had been installed on my machine, `font-della-respira` and `font-goudy-bookletter-1911` are still definitely present on Google Fonts[1][2].

[1] https://fonts.google.com/specimen/Della+Respira
[2] https://fonts.google.com/specimen/Goudy+Bookletter+1911

### Command that failed

brew update

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor` and `brew config`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by CatGreen90** [comment]
I believe all of the fonts removed had their METADATA.pb files edited in this commit: https://github.com/google/fonts/commit/47a6c224b3e0287b2e48e3ffef8c9ce2ca4931f4

The same thing happened back in February, but it only affected 3 fonts that time: https://github.com/Homebrew/homebrew-cask-fonts/issues/6964

**Comment by toobuntu** [comment]
Resolved by https://github.com/Homebrew/homebrew-cask-fonts/pull/8130
