### ISSUE TITLE
Some fonts are redownloaded/reinstalled with every `brew upgrade` even when no changes are in those fonts

### ISSUE THREAD

**Issue by duanemoody** [Homebrew/homebrew-cask-fonts#8193]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

`brew upgrade --greedy` causes several Google fonts to be redownloaded and reinstalled even when there are no changes in the fonts' repos:

- font-tuffy
- font-titillium-web
- font-roboto
- font-rem
- font-open-sans
- font-life-savers
- font-lekton
- font-fruktur
- font-changa-one
- font-cabin-condensed
- font-cabin

Several other fonts installed via brew do not exhibit this behavior and only update when changes are made in their respective repos, _e.g._ `font-iosevka`, `font-fira-sans`, `font-lato`, etc. No other brew formulae/casks outside of these fonts are redownloaded/reinstalled like this, either. 

### Command that failed

brew upgrade --greedy

### Output of command with `--verbose --debug`

```shell
(full log too long)
==> Verifying Gatekeeper status of /Users/duanemoody/Library/Caches/Homebrew/downloads/53b989c0bb894aa0dc2bbd48f6548c8a4bfde6497af0de8c27d99c3297e766d3--Righteous-Regular.ttf
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/duanemoody/Library/Caches/Homebrew/downloads/53b989c0bb894aa0dc2bbd48f6548c8a4bfde6497af0de8c27d99c3297e766d3--Righteous-Regular.ttf
==> /Users/duanemoody/Library/Caches/Homebrew/downloads/53b989c0bb894aa0dc2bbd48f6548c8a4bfde6497af0de8c27d99c3297e766d3--Righteous-Regular.ttf is quarantined
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.8\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/google/fonts/raw/main/apache/robotoslab/RobotoSlab\%5Bwght\%5D.ttf
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.8\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/google/fonts/raw/main/apache/robotoslab/RobotoSlab\%5Bwght\%5D.ttf
==> Verifying Gatekeeper status of /Users/duanemoody/Library/Caches/Homebrew/downloads/8e609cbb9138e915336c0667ace25b3a27f2d6d78b81ff74a5dc20f1e6b5a123--RobotoSlab[wght].ttf
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/duanemoody/Library/Caches/Homebrew/downloads/8e609cbb9138e915336c0667ace25b3a27f2d6d78b81ff74a5dc20f1e6b5a123--RobotoSlab\[wght\].ttf
==> /Users/duanemoody/Library/Caches/Homebrew/downloads/8e609cbb9138e915336c0667ace25b3a27f2d6d78b81ff74a5dc20f1e6b5a123--RobotoSlab[wght].ttf is quarantined
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.8\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/google/fonts/raw/main/ofl/vt323/VT323-Regular.ttf
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.8\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://github.com/google/fonts/raw/main/ofl/vt323/VT323-Regular.ttf
==> Verifying Gatekeeper status of /Users/duanemoody/Library/Caches/Homebrew/downloads/34e055b5215b3becad4eede7a3ed4da54d90a89273a7e56d0d99cf9b10a021a2--VT323-Regular.ttf
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/duanemoody/Library/Caches/Homebrew/downloads/34e055b5215b3becad4eede7a3ed4da54d90a89273a7e56d0d99cf9b10a021a2--VT323-Regular.ttf
==> /Users/duanemoody/Library/Caches/Homebrew/downloads/34e055b5215b3becad4eede7a3ed4da54d90a89273a7e56d0d99cf9b10a021a2--VT323-Regular.ttf is quarantined
==> Upgrading 1 outdated package:
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /usr/local/Caskroom/font-cabin/.metadata/latest/20230828154244.101/Casks/font-cabin.rb
font-cabin latest -> latest
==> Started upgrade process for Cask font-cabin
==> Upgrading font-cabin
==> Printing caveats
==> Cask::Installer#fetch
==> Cloning https://github.com/google/fonts.git
/usr/bin/env git --git-dir /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/.git status -s
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
/usr/bin/env git config remote.origin.url https://github.com/google/fonts.git
/usr/bin/env git config remote.origin.fetch \+refs/heads/main:refs/remotes/origin/main
/usr/bin/env git config remote.origin.tagOpt --no-tags
/usr/bin/env git config advice.detachedHead false
/usr/bin/env git config core.fsmonitor false
/usr/bin/env git config origin.partialclonefilter blob:none
/usr/bin/env git config core.sparseCheckout true
/usr/bin/env git config core.sparseCheckoutCone true
/usr/bin/env git fetch origin
==> Checking out branch main
/usr/bin/env git checkout -f main --
Already on 'main'
Your branch is up to date with 'origin/main'.
/usr/bin/env git reset --hard origin/main --
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
/usr/bin/env git submodule foreach --recursive git\ submodule\ sync
/usr/bin/env git submodule update --init --recursive
/usr/bin/env git submodule --quiet foreach --recursive pwd
==> Verifying Gatekeeper status of /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
==> /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse is quarantined
Warning: No checksum defined for cask 'font-cabin', skipping verification.
/usr/bin/env hdiutil imageinfo -format /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
==> Uninstalling artifacts
==> 2 artifacts defined
#<Cask::ArtifactSet: {#<Cask::Artifact::Font:0x00007f9e71145700 @cask=#<Cask font-cabin /usr/local/Caskroom/font-cabin/.metadata/latest/20230828154244.101/Casks/font-cabin.rb>, @dsl_args=["Cabin-Italic[wdth,wght].ttf", {}], @source_string="Cabin-Italic[wdth,wght].ttf", @target_string="">, #<Cask::Artifact::Font:0x00007f9e71145278 @cask=#<Cask font-cabin /usr/local/Caskroom/font-cabin/.metadata/latest/20230828154244.101/Casks/font-cabin.rb>, @dsl_args=["Cabin[wdth,wght].ttf", {}], @source_string="Cabin[wdth,wght].ttf", @target_string="">}>
==> Uninstalling artifact of class Cask::Artifact::Font
==> Backing Font 'Cabin-Italic[wdth,wght].ttf' up to '/usr/local/Caskroom/font-cabin/latest/ofl/cabin/Cabin-Italic[wdth,wght].ttf'
/usr/bin/env /bin/cp -pR /Users/duanemoody/Library/Fonts/Cabin-Italic\[wdth,wght\].ttf /usr/local/Caskroom/font-cabin/latest/ofl/cabin/Cabin-Italic\[wdth,wght\].ttf
==> Removing Font '/Users/duanemoody/Library/Fonts/Cabin-Italic[wdth,wght].ttf'
==> Uninstalling artifact of class Cask::Artifact::Font
==> Backing Font 'Cabin[wdth,wght].ttf' up to '/usr/local/Caskroom/font-cabin/latest/ofl/cabin/Cabin[wdth,wght].ttf'
/usr/bin/env /bin/cp -pR /Users/duanemoody/Library/Fonts/Cabin\[wdth,wght\].ttf /usr/local/Caskroom/font-cabin/latest/ofl/cabin/Cabin\[wdth,wght\].ttf
==> Removing Font '/Users/duanemoody/Library/Fonts/Cabin[wdth,wght].ttf'
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Git for /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/TRIVIA.md /private/tmp/d20230828-91146-19g50k0/TRIVIA.md
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/CODE_OF_CONDUCT.md /private/tmp/d20230828-91146-19g50k0/CODE_OF_CONDUCT.md
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/ofl/. /private/tmp/d20230828-91146-19g50k0/ofl
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/.gitmodules /private/tmp/d20230828-91146-19g50k0/.gitmodules
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/README.md /private/tmp/d20230828-91146-19g50k0/README.md
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/.gitignore /private/tmp/d20230828-91146-19g50k0/.gitignore
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/CONTRIBUTING.md /private/tmp/d20230828-91146-19g50k0/CONTRIBUTING.md
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/.gitattributes /private/tmp/d20230828-91146-19g50k0/.gitattributes
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/to_production.txt /private/tmp/d20230828-91146-19g50k0/to_production.txt
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/.git/. /private/tmp/d20230828-91146-19g50k0/.git
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/AUTHORS.txt /private/tmp/d20230828-91146-19g50k0/AUTHORS.txt
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/to_sandbox.txt /private/tmp/d20230828-91146-19g50k0/to_sandbox.txt
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/CONTRIBUTORS.txt /private/tmp/d20230828-91146-19g50k0/CONTRIBUTORS.txt
/usr/bin/env cp -pR /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse/to_delist.txt /private/tmp/d20230828-91146-19g50k0/to_delist.txt
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/TRIVIA.md /usr/local/Caskroom/font-cabin/latest/TRIVIA.md
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/CODE_OF_CONDUCT.md /usr/local/Caskroom/font-cabin/latest/CODE_OF_CONDUCT.md
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/ofl/. /usr/local/Caskroom/font-cabin/latest/ofl
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/.gitmodules /usr/local/Caskroom/font-cabin/latest/.gitmodules
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/README.md /usr/local/Caskroom/font-cabin/latest/README.md
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/.gitignore /usr/local/Caskroom/font-cabin/latest/.gitignore
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/CONTRIBUTING.md /usr/local/Caskroom/font-cabin/latest/CONTRIBUTING.md
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/.gitattributes /usr/local/Caskroom/font-cabin/latest/.gitattributes
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/to_production.txt /usr/local/Caskroom/font-cabin/latest/to_production.txt
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/.git/. /usr/local/Caskroom/font-cabin/latest/.git
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/AUTHORS.txt /usr/local/Caskroom/font-cabin/latest/AUTHORS.txt
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/to_sandbox.txt /usr/local/Caskroom/font-cabin/latest/to_sandbox.txt
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/CONTRIBUTORS.txt /usr/local/Caskroom/font-cabin/latest/CONTRIBUTORS.txt
/usr/bin/env cp -pR /private/tmp/d20230828-91146-19g50k0/to_delist.txt /usr/local/Caskroom/font-cabin/latest/to_delist.txt
==> Verifying Gatekeeper status of /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
==> /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse is quarantined
==> Propagating quarantine from /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse to /usr/local/Caskroom/font-cabin/latest
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;64e38934\;Homebrew\\x20Cask\;A8EB8456-0E89-4CAA-829F-8C650B1C7A34
==> Creating metadata directory: /usr/local/Caskroom/font-cabin/.metadata/latest/20230828155348.737
==> Creating metadata subdirectory: /usr/local/Caskroom/font-cabin/.metadata/latest/20230828155348.737/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Font
==> Moving Font 'Cabin-Italic[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/Cabin-Italic[wdth,wght].ttf'
==> Installing artifact of class Cask::Artifact::Font
==> Moving Font 'Cabin[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/Cabin[wdth,wght].ttf'
==> Purging files for version latest of Cask font-cabin
🍺  font-cabin was successfully upgraded!
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor: `Your system is ready to brew.`
brew config:
`HOMEBREW_VERSION: 4.1.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d4444b563e24ac7c05a93121c464c02dfa04d44f
Last commit: 20 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6deab78cec6ffe8941706f3afb7a39e7f9d49f14
Core tap last commit: 36 minutes ago
Core tap branch: master
Core tap JSON: 28 Aug 15:53 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.7seEnifoyO/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 14.0.0 build 1400
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.6.8-x86_64
CLT: 14.0.0.29.202
Xcode: 14.2`
```

### Output of `brew tap`

```shell
acrogenesis/macchanger
adymo/kde
carlocab/personal
gcenx/wine
gromgit/fuse
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
mpv-player/mpv
nativeos/i386-elf-toolchain
ytsutano/toolbox
```

**Comment by duanemoody** [comment]
**Note:** The example command output shown above is after those fonts were removed and only `font-cabin` reinstalled via brew: the results for each of the fonts referred to are the same as with `font-cabin`. 
Here's the log from reinstalling all those fonts (notice all of them have `Warning: No checksum defined for cask 'font-rem', skipping verification.`):
`$ brew install font-tuffy font-titillium-web font-roboto font-rem font-open-sans font-life-savers font-lekton font-fruktur font-changa-one font-cabin-condensed font-cabin
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################### 100.0%
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-tuffy--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-tuffy', skipping verification.
==> Installing Cask font-tuffy
==> Moving Font 'Tuffy-Bold.ttf' to '/Users/duanemoody/Library/Fonts/Tuffy-Bold.ttf'
==> Moving Font 'Tuffy-BoldItalic.ttf' to '/Users/duanemoody/Library/Fonts/Tuffy-BoldItalic.ttf'
==> Moving Font 'Tuffy-Italic.ttf' to '/Users/duanemoody/Library/Fonts/Tuffy-Italic.ttf'
==> Moving Font 'Tuffy-Regular.ttf' to '/Users/duanemoody/Library/Fonts/Tuffy-Regular.ttf'
🍺  font-tuffy was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-titillium-web--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-titillium-web', skipping verification.
==> Installing Cask font-titillium-web
==> Moving Font 'TitilliumWeb-SemiBoldItalic.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-SemiBoldItalic.ttf'
==> Moving Font 'TitilliumWeb-Bold.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-Bold.ttf'
==> Moving Font 'TitilliumWeb-BoldItalic.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-BoldItalic.ttf'
==> Moving Font 'TitilliumWeb-ExtraLight.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-ExtraLight.ttf'
==> Moving Font 'TitilliumWeb-ExtraLightItalic.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-ExtraLightItalic.ttf'
==> Moving Font 'TitilliumWeb-Italic.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-Italic.ttf'
==> Moving Font 'TitilliumWeb-Light.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-Light.ttf'
==> Moving Font 'TitilliumWeb-LightItalic.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-LightItalic.ttf'
==> Moving Font 'TitilliumWeb-Regular.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-Regular.ttf'
==> Moving Font 'TitilliumWeb-SemiBold.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-SemiBold.ttf'
==> Moving Font 'TitilliumWeb-Black.ttf' to '/Users/duanemoody/Library/Fonts/TitilliumWeb-Black.ttf'
🍺  font-titillium-web was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-roboto--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-roboto', skipping verification.
==> Installing Cask font-roboto
==> Moving Font 'Roboto-Italic[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/Roboto-Italic[wdth,wght].ttf'
==> Moving Font 'Roboto[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/Roboto[wdth,wght].ttf'
🍺  font-roboto was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-rem--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-rem', skipping verification.
==> Installing Cask font-rem
==> Moving Font 'REM-Italic[wght].ttf' to '/Users/duanemoody/Library/Fonts/REM-Italic[wght].ttf'
==> Moving Font 'REM[wght].ttf' to '/Users/duanemoody/Library/Fonts/REM[wght].ttf'
🍺  font-rem was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-open-sans--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-open-sans', skipping verification.
==> Installing Cask font-open-sans
==> Moving Font 'OpenSans-Italic[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/OpenSans-Italic[wdth,wght].ttf'
==> Moving Font 'OpenSans[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/OpenSans[wdth,wght].ttf'
🍺  font-open-sans was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-life-savers--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-life-savers', skipping verification.
==> Installing Cask font-life-savers
==> Moving Font 'LifeSavers-Bold.ttf' to '/Users/duanemoody/Library/Fonts/LifeSavers-Bold.ttf'
==> Moving Font 'LifeSavers-ExtraBold.ttf' to '/Users/duanemoody/Library/Fonts/LifeSavers-ExtraBold.ttf'
==> Moving Font 'LifeSavers-Regular.ttf' to '/Users/duanemoody/Library/Fonts/LifeSavers-Regular.ttf'
🍺  font-life-savers was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-lekton--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-lekton', skipping verification.
==> Installing Cask font-lekton
==> Moving Font 'Lekton-Bold.ttf' to '/Users/duanemoody/Library/Fonts/Lekton-Bold.ttf'
==> Moving Font 'Lekton-Italic.ttf' to '/Users/duanemoody/Library/Fonts/Lekton-Italic.ttf'
==> Moving Font 'Lekton-Regular.ttf' to '/Users/duanemoody/Library/Fonts/Lekton-Regular.ttf'
🍺  font-lekton was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-fruktur--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-fruktur', skipping verification.
==> Installing Cask font-fruktur
==> Moving Font 'Fruktur-Italic.ttf' to '/Users/duanemoody/Library/Fonts/Fruktur-Italic.ttf'
==> Moving Font 'Fruktur-Regular.ttf' to '/Users/duanemoody/Library/Fonts/Fruktur-Regular.ttf'
🍺  font-fruktur was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-changa-one--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-changa-one', skipping verification.
==> Installing Cask font-changa-one
==> Moving Font 'ChangaOne-Italic.ttf' to '/Users/duanemoody/Library/Fonts/ChangaOne-Italic.ttf'
==> Moving Font 'ChangaOne-Regular.ttf' to '/Users/duanemoody/Library/Fonts/ChangaOne-Regular.ttf'
🍺  font-changa-one was successfully installed!
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin-condensed--git-sparse
From https://github.com/google/fonts
   8857a069..25fdc5d3  main       -> origin/main
==> Checking out branch main
Already on 'main'
Your branch is behind 'origin/main' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-cabin-condensed', skipping verification.
==> Installing Cask font-cabin-condensed
==> Moving Font 'CabinCondensed-Bold.ttf' to '/Users/duanemoody/Library/Fonts/CabinCondensed-Bold.ttf'
==> Moving Font 'CabinCondensed-Medium.ttf' to '/Users/duanemoody/Library/Fonts/CabinCondensed-Medium.ttf'
==> Moving Font 'CabinCondensed-Regular.ttf' to '/Users/duanemoody/Library/Fonts/CabinCondensed-Regular.ttf'
==> Moving Font 'CabinCondensed-SemiBold.ttf' to '/Users/duanemoody/Library/Fonts/CabinCondensed-SemiBold.ttf'
🍺  font-cabin-condensed was successfully installed!
==> Upgrading 1 outdated package:
font-cabin latest -> latest
==> Upgrading font-cabin
==> Cloning https://github.com/google/fonts.git
Updating /Users/duanemoody/Library/Caches/Homebrew/Cask/font-cabin--git-sparse
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at 25fdc5d3 Update to_prod & to_sand lists for Fri Aug 25th
Warning: No checksum defined for cask 'font-cabin', skipping verification.
==> Backing Font 'Cabin-Italic[wdth,wght].ttf' up to '/usr/local/Caskroom/font-cabin/latest/ofl/cabin/Cabin-Italic[wdth,wght].tt
==> Removing Font '/Users/duanemoody/Library/Fonts/Cabin-Italic[wdth,wght].ttf'
==> Backing Font 'Cabin[wdth,wght].ttf' up to '/usr/local/Caskroom/font-cabin/latest/ofl/cabin/Cabin[wdth,wght].ttf'
==> Removing Font '/Users/duanemoody/Library/Fonts/Cabin[wdth,wght].ttf'
==> Moving Font 'Cabin-Italic[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/Cabin-Italic[wdth,wght].ttf'
==> Moving Font 'Cabin[wdth,wght].ttf' to '/Users/duanemoody/Library/Fonts/Cabin[wdth,wght].ttf'
==> Purging files for version latest of Cask font-cabin
🍺  font-cabin was successfully upgraded!`

**Comment by bevanjkay** [comment]
@duanemoody This is because the fonts have no version information available. The version is `:latest` - using `brew upgrade --greedy` will upgrade these fonts every time as we have no way of knowing if they have been updated or not. 

You could try using `brew upgrade --greedy-auto-updates` instead which will upgrade casks with `auto_updates true` set but not those with `version :latest`.
