### ISSUE TITLE
DOC: Discoverability of available fonts?

### ISSUE THREAD

**Issue by Offirmo** [Homebrew/homebrew-cask-fonts#9041]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I need to install Microsoft's Segoe UI for compatibility reasons. I don't know if it's in homebrew-cask-fonts but I tried to check if it was.

Unfortunately I can't see the list of available fonts:

- Looking at the code, GitHub truncates the list of fonts "1161 entries not shown"
- homebrew home page doesn't show any font when using the search

Did I miss something?

If there is a way to search for available fonts, I suggest mentioning it on the README of this project. Thanks!

### Command that failed

n/a

### Output of command with `--verbose --debug`

```shell
n/a
```

### Output of `brew doctor` and `brew config`

```shell
n/a
```

### Output of `brew tap`

```shell
n/a
```

**Comment by Offirmo** [comment]
This is a DOC issue for this SPECIFIC project, sorry for abusing the bug report, I believe it's valid.

**Comment by bevanjkay** [comment]
@Offirmo The relevant information is found in the `homebrew-cask` [repo](https://github.com/Homebrew/homebrew-cask), which is the first link in this repo's README.md
